# https://taskfile.dev

version: '3'

dotenv:
  - .env

tasks:
  default:
    desc: "Gettings started"
    cmds:
      - task: install
  
  install:
    desc: "Install dependencies"
    cmds:
      - go mod download
      - go install github.com/air-verse/air@latest
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/bufbuild/buf/cmd/buf@v1.48.0
      - go install github.com/vektra/mockery/v2@v2.50.0
      - go install github.com/google/yamlfmt/cmd/yamlfmt@latest

  service:up:
    desc: "Start the service"
    cmd: docker compose up -d
  
  service:down:
    desc: "Stop services"
    cmd: docker compose down
  
  test:
    desc: "Run tests"
    cmds:
      - go test -v ./... -race -cover -timeout 30s -count 1 -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html